import nodemailer from 'nodemailer';
import fs from 'fs/promises';
import path from 'path';

interface EmailAttachment {
  filename: string;
  path: string;
  contentType?: string;
}

/**
 * Sends an email with optional attachments
 * @param to Recipient email address
 * @param subject Email subject
 * @param body Email body content (HTML supported)
 * @param attachments Optional array of file paths to attach
 */
export const sendEmail = async (
  to: string,
  subject: string,
  body: string,
  attachments: EmailAttachment[] = []
): Promise<boolean> => {
  try {
    // Create a transporter using environment variables
    const transporter = nodemailer.createTransport({
      host: process.env.NEXT_PUBLIC_EMAIL_HOST || process.env.EMAIL_HOST,
      port: parseInt(process.env.NEXT_PUBLIC_EMAIL_PORT || process.env.EMAIL_PORT || '587'),
      secure: (process.env.NEXT_PUBLIC_EMAIL_SECURE || process.env.EMAIL_SECURE) === 'true',
      auth: {
        user: process.env.NEXT_PUBLIC_EMAIL_USER || process.env.EMAIL_USER,
        pass: process.env.NEXT_PUBLIC_EMAIL_PASSWORD || process.env.EMAIL_PASSWORD
      }
    });

    // Send the email
    const info = await transporter.sendMail({
      from: process.env.NEXT_PUBLIC_EMAIL_FROM || process.env.EMAIL_FROM || 'noreply@parealestatesupport.com',
      to,
      subject,
      html: body,
      attachments
    });

    console.log('Email sent successfully:', info.messageId);
    return true;
  } catch (error) {
    console.error('Error sending email:', error);
    return false;
  }
};

/**
 * Sends a cover sheet PDF as an email attachment
 * @param pdfPath Path to the generated PDF file
 * @param transactionData Data about the transaction for the email subject/body
 */
export const sendCoverSheetEmail = async (
  pdfPath: string,
  transactionData: {
    address: string;
    mlsNumber: string;
    agentRole: string;
    agentName: string;
  }
): Promise<boolean> => {
  try {
    // Verify the file exists
    await fs.access(pdfPath);
    
    // Get the filename from the path
    const filename = path.basename(pdfPath);
    
    // Create meaningful subject and body
    const subject = `Cover Sheet - ${transactionData.address} (MLS #${transactionData.mlsNumber})`;
    const body = `
      <h2>Transaction Cover Sheet</h2>
      <p><strong>Property:</strong> ${transactionData.address}</p>
      <p><strong>MLS #:</strong> ${transactionData.mlsNumber}</p>
      <p><strong>Agent Role:</strong> ${transactionData.agentRole}</p>
      <p><strong>Agent Name:</strong> ${transactionData.agentName}</p>
      <p>The transaction cover sheet is attached to this email.</p>
      <p>This email was automatically generated by the PA Real Estate Support Services system.</p>
    `;
    
    // Send the email
    return await sendEmail(
      'debbie@parealestatesupport.com',
      subject,
      body,
      [
        {
          filename,
          path: pdfPath,
          contentType: 'application/pdf'
        }
      ]
    );
  } catch (error) {
    console.error('Error sending cover sheet email:', error);
    return false;
  }
}; 